console_title_template = "{{ .Shell }} in {{ .Folder }}"
version = 3
final_space = true
auto_upgrade = true

[secondary_prompt]
template = "❯❯ "
foreground = "magenta"
background = "transparent"

[transient_prompt]
template = "❯ "
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "path"
style = "plain"
template = "{{ .Path }}"
foreground = "green"
background = "transparent"

[blocks.segments.properties]
cache_duration = "none"
style = "full"

[[blocks.segments]]
type = "git"
style = "plain"
template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"
foreground = "p:grey"
background = "transparent"

[blocks.segments.properties]
branch_icon = ""
cache_duration = "none"
commit_icon = "@"
fetch_status = true

[[blocks]]
type = "rprompt"
overflow = "hidden"

[[blocks.segments]]
type = "status"
style = "plain"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}green{{end}}",
]
background = "transparent"
template = "{{ .String }} "

[[blocks.segments]]
type = "executiontime"
style = "plain"
template = "{{ .FormattedMs }}"
foreground = "yellow"
background = "transparent"

[blocks.segments.properties]
cache_duration = "none"
threshold = 5000

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
template = "❯"
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]

[blocks.segments.properties]
cache_duration = "none"

[[tooltips]]
type = "docker"
tips = ["docker", "d"]
style = "plain"
foreground = "p:grey"
background = "transparent"
template = "  {{ .Context }}"

[[tooltips]]
type = "kubectl"
tips = ["kubectl", "k"]
style = "plain"
foreground = "p:grey"
background = "transparent"
template = " ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"

[[tooltips]]
type = "go"
tips = ["go"]
style = "plain"
foreground = "p:grey"
background = "transparent"
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"

[tooltips.properties]
parse_mod_file = true
parse_go_work_file = true

[[tooltips]]
type = "node"
tips = ["node", "pnpm"]
style = "plain"
foreground = "p:grey"
background = "transparent"
template = " {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"

[tooltips.properties]
fetch_package_manager = true
